version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:3000"  # Map to port 80 for easier access
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/postgres
      - NODE_ENV=production
      - NEXTAUTH_URL=http://52.207.251.16
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
